# This is a basic workflow to help you get started with Actions

name: CI Build Status

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: guitar24t/ck-ros:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /tmp
          git clone https://github.com/frcteam195/ros-ci-helper
          git clone --recurse-submodules https://github.com/frcteam195/third_party_libs
          cd third_party_libs
          ../ros-ci-helper/make_third_party_libs.sh
          mkdir -p Robot/catkin_ws/src
          cd ../Robot/catkin_ws/src
          cp -R $GITHUB_WORKSPACE ./
          ../../ros-ci-helper/fetch_ros_dependencies.sh $GITHUB_WORKSPACE/package.xml
          cd ..
          source /opt/ros/melodic/setup.bash
          catkin_make -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra" -DCATKIN_ENABLE_TESTING=0
        shell: bash
